# TODO: revert to template name
# name = "{{project-name}}"
name = "rustwasm-worker-template"

workers_dev = true
compatibility_date = "2023-10-27"
main = "build/worker/shim.mjs"

# routes = [
#   { pattern = "this-thing.your-domain.com", custom_domain = true }
# ]

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
